version: '3.8'

services:
  database:
    image: postgres
    container_name: laravel_aula_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USERNAME: root
      POSTGRES_DB: ainetz_aula
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5436:5432'
    networks:
      - app_network
  php-apache:
    container_name: laravel_aula_apache
    build:
      context: php
    ports:
      - '8080:8090'
    volumes:
      - ./src:/var/www/laravel_docker
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - database 
    networks:
      - app_network
  app:
    build: .
    container_name: laravel_aula_app
    command: >-
      sh -c "
        apk add php8-pecl-xdebug && composer install ;\
        cp .docker/xdebug.ini /etc/php8/conf.d/50_xdebug.ini ;\
        php artisan serve --host 0.0.0.0 --port 80"
    ports:
      - "8000:80"
    env_file:
      - ./src/.env
    volumes:
      - .docker/xdebug.ini
      - .:/var/www/html:rw
    networks:
      - app_network
  redis:
    image: redis:alpine
    container_name: laravel_aula_cache
    ports:
      - "6379:6379"
    volumes:
      - cache_data:/data
    networks:
      - app_network
volumes:
  db_data:
    driver: "local"
  cache_data:
    driver: "local"

networks:
  app_network:
    driver: "bridge"

