version: "3.7"
services:
  app:
    build:
      args:
        user: ciclano
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: aula-laravel
    depends_on:
        -   db
    container_name: aula_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - aula-laravel

  db:
    image: mysql:5.7
    container_name: aula_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - aula-laravel

  nginx:
    image: nginx:alpine
    container_name: aula-laravel-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - aula-laravel
  adminer:
      image: adminer
      ports:
          - 8080:8080
      networks:
          - aula-laravel

networks:
  aula-laravel:
    driver: bridge
